<template>
  <div>
    <b-table striped hover :items="bangumis" :fields="bangumis_fields">
      <template #cell(season_id)="data">
        <a
          rel="noreferrer"
          target="_blank"
          :href="'https://global.bilibili.com/play/ss' + data.value"
          :click="$ga.event('bilibili_sea', 'click', 'ss', data.value)"
          >{{ data.value }}</a
        >
      </template>
    </b-table>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'
export default Vue.extend({
  data() {
    return {
      bangumis_fields: [
        {
          key: 'season_id',
          sortable: true,
        },
        {
          key: 'title',
          sortable: true,
        },
      ],
      bangumis: [
        { season_id: 34395, title: '宝石之国' },
        { season_id: 34444, title: 'OVERLORD III' },
        { season_id: 34445, title: '因为太怕痛就全点防御力了' },
        { season_id: 34450, title: '同居人是猫' },
        { season_id: 34465, title: '排球少年！！才能与感觉' },
        { season_id: 34466, title: '排球少年！！观念之战' },
        { season_id: 34467, title: '排球少年！！结束与开始' },
        { season_id: 34468, title: '排球少年！！胜者与败者' },
        { season_id: 34475, title: '排球少年！！' },
        { season_id: 34482, title: '请问您今天要来点兔子吗？？' },
        { season_id: 34491, title: '魔法科高中的劣等生呼唤繁星的少女' },
        { season_id: 34495, title: '排球少年！！第四季 Part1' },
        { season_id: 34500, title: '请问您今天要来点兔子吗？' },
        {
          season_id: 34501,
          title: '请问您今天要来点兔子吗？？～Dear My Sister～',
        },
        {
          season_id: 34502,
          title: '请问您今天要来点兔子吗？？～Sing For You～',
        },
        {
          season_id: 34505,
          title: 'Fate/kaleid liner 魔法少女☆伊莉雅 雪下的誓言',
        },
        { season_id: 34508, title: '地狱少女' },
        { season_id: 34521, title: '进击的巨人 第二季' },
        { season_id: 34523, title: 'Re：从零开始的异世界生活 Memory Snow' },
        { season_id: 34526, title: 'Re：从零开始的异世界生活 冰结之绊' },
        { season_id: 34528, title: 'OVERLORD II' },
        { season_id: 34529, title: '魔法禁书目录' },
        { season_id: 34531, title: '魔法禁书目录 Ⅱ' },
        { season_id: 34537, title: '某科学的超电磁炮' },
        { season_id: 34539, title: '进击的巨人 第三季 Part2' },
        { season_id: 34542, title: '某科学的超电磁炮S' },
        { season_id: 34546, title: '地狱少女 宵伽' },
        { season_id: 34552, title: '辉夜姬想让人告白？～天才们的恋爱头脑战～' },
        { season_id: 34557, title: '食戟之灵 神之皿' },
        { season_id: 34558, title: '为美好的世界献上祝福！' },
        { season_id: 34560, title: '排球少年！！第二季' },
        { season_id: 34572, title: '食戟之灵' },
        { season_id: 34574, title: '刀剑神域 Alicization' },
        { season_id: 34575, title: '果然我的青春恋爱喜剧搞错了。续' },
        { season_id: 34578, title: '魔法禁书目录 剧场版' },
        { season_id: 34579, title: '排球少年！！第三季' },
        { season_id: 34580, title: '鬼灭之刃' },
        { season_id: 34581, title: '东京喰种:re Part1' },
        { season_id: 34583, title: '为美好的世界献上祝福！ 第二季' },
        { season_id: 34586, title: '工作细胞' },
        { season_id: 34587, title: 'Anima Yell!' },
        { season_id: 34604, title: 'Ｄｒ．ＳＴＯＮＥ 石纪元' },
        { season_id: 34606, title: '约战狂三外传' },
        { season_id: 34611, title: '进击的巨人 第三季 Part1' },
        { season_id: 34612, title: '月歌。THE ANIMATION S2' },
        { season_id: 34613, title: '总之就是非常可爱' },
        { season_id: 34628, title: '终将成为你' },
        { season_id: 34634, title: '排球少年！！第四季 Part2' },
        { season_id: 34638, title: '大贵族' },
        { season_id: 34641, title: '请问您今天要来点兔子吗？BLOOM' },
        { season_id: 34642, title: '在地下城寻求邂逅是否搞错了什么 第三季' },
        { season_id: 34643, title: '忧国的莫里亚蒂' },
        { season_id: 34644, title: '在魔王城说晚安' },
        { season_id: 34645, title: '欢迎来到实力至上主义的教室' },
        { season_id: 34648, title: '半妖的夜叉姫' },
        { season_id: 34651, title: '成神之日' },
        { season_id: 34652, title: '满溢的水果挞' },
        { season_id: 34653, title: '碧蓝航线' },
        { season_id: 34657, title: '体操武士 ' },
        { season_id: 34663, title: '理科生坠入情网，故尝试证明之' },
        { season_id: 34677, title: '池袋西口公园' },
        { season_id: 34678, title: 'Burn the Witch 龙与魔女' },
        { season_id: 34679, title: '你与我最后的战场，亦或是世界起始的圣战' },
        { season_id: 34682, title: '八男？别闹了！' },
        { season_id: 34693, title: '时之歌 - 花与焰的狂想诗' },
        { season_id: 34694, title: '我开动物园那些年' },
        { season_id: 34695, title: '仙王的日常生活' },
        { season_id: 34701, title: '影鳄' },
        { season_id: 34709, title: '阿尔蒂' },
        { season_id: 34722, title: 'JOJO的奇妙冒险 不灭钻石' },
        { season_id: 34725, title: '少女终末旅行' },
        { season_id: 34728, title: '我们无法一起学习' },
        { season_id: 34735, title: '非枪人生 NO GUNS LIFE' },
        { season_id: 34736, title: '弩级战队H×EROS' },
        { season_id: 34764, title: ' 装甲重拳' },
        { season_id: 34771, title: '一个人的〇〇小日子' },
        { season_id: 34780, title: '东京喰种:re Part2' },
        { season_id: 34781, title: '干物妹！小埋' },
        { season_id: 34791, title: 'JOJO的奇妙冒险' },
        {
          season_id: 34795,
          title: 'Fate/kaleid liner 魔法少女☆伊莉雅 3rei！！',
        },
        { season_id: 34796, title: 'JOJO的奇妙冒险 黄金之风' },
        { season_id: 34797, title: '魔物娘的医生' },
        { season_id: 34801, title: '幻想玩偶' },
        { season_id: 34807, title: '学战都市Asterisk 第二季' },
        { season_id: 34812, title: '学战都市Asterisk' },
        { season_id: 34820, title: '非枪人生 NO GUNS LIFE 第二季' },
        { season_id: 34822, title: 'RErideD - 穿越时空的德希达 -' },
        { season_id: 34825, title: '青之驱魔师' },
        { season_id: 34829, title: '彗星路西法' },
        { season_id: 34830, title: '火之丸相扑' },
        { season_id: 34834, title: 'ViVid Strike!' },
        { season_id: 34835, title: '万国志' },
        { season_id: 34837, title: '刀剑神域外传 Gun Gale Online' },
        { season_id: 34844, title: 'UQ HOLDER！悠久持有者！OVA' },
        { season_id: 34847, title: '斯特拉的魔法' },
        { season_id: 34859, title: 'Just Because! ' },
        { season_id: 34865, title: '刀剑神域 Extra Edition' },
        { season_id: 34866, title: '龙王的工作！' },
        { season_id: 34867, title: '博多豚骨拉面团' },
        { season_id: 34876, title: '中间管理录利根川' },
        { season_id: 34877, title: '只要别西卜大小姐喜欢就好' },
        {
          season_id: 34879,
          title: '路人超能100 REIGEN～不为人知的奇迹灵能者～',
        },
        { season_id: 34884, title: '干物妹！小埋R' },
        { season_id: 34890, title: '多田君不恋爱' },
        { season_id: 34895, title: '粉彩回忆' },
        { season_id: 34896, title: '付丧神出租中！' },
        { season_id: 34905, title: '羽球战争！' },
        { season_id: 34907, title: '强风吹拂' },
        { season_id: 34912, title: '路人超能100 第二季' },
        { season_id: 34916, title: '落第骑士英雄谭' },
        { season_id: 34926, title: 'A3!满开剧团' },
        { season_id: 34930, title: 'BanG Dream!' },
        { season_id: 34931, title: 'BanG Dream! 第二季' },
        { season_id: 34937, title: 'BanG Dream! 第三季' },
        { season_id: 34939, title: 'BanG Dream! 电影演唱会' },
        { season_id: 34957, title: '暗芝居 第五季' },
        { season_id: 34961, title: '宝石商人理察的谜鉴定' },
        { season_id: 34975, title: '盾之勇者成名录' },
        { season_id: 34993, title: '熊巫女' },
        { season_id: 35041, title: '初恋怪兽' },
        { season_id: 35042, title: '雏子的笔记' },
        { season_id: 35044, title: '进击的巨人' },
        { season_id: 35051, title: '洲崎西 THE ANIMATION' },
        { season_id: 35053, title: '橘色奇迹' },
        { season_id: 35087, title: '未确认进行式' },
        { season_id: 35089, title: '竞女!!!!!!!!' },
        { season_id: 35090, title: '我家的女仆有够烦！' },
        { season_id: 35095, title: '刀剑神域剧场版：序列争战' },
        { season_id: 35107, title: 'Fate/kaleid liner 魔法少女☆伊莉雅' },
        { season_id: 35108, title: '千绪的通学路' },
        { season_id: 35109, title: 'Fate/kaleid liner 魔法少女☆伊莉雅 2wei！' },
        { season_id: 35121, title: '四月是你的谎言' },
        { season_id: 35122, title: '斩！赤红之瞳' },
        { season_id: 35123, title: 'NO GAME NO LIFE 游戏人生' },
        {
          season_id: 35129,
          title: 'Fate/kaleid liner 魔法少女☆伊莉雅 2wei Herz！',
        },
        { season_id: 35139, title: '比宇宙更远的地方' },
        { season_id: 35149, title: '如果折断她的旗' },
        { season_id: 35150, title: '青之驱魔师 京都不净王篇' },
        { season_id: 35176, title: '强袭魔女 通往柏林之路' },
        { season_id: 35186, title: '非洲的动物上班族' },
        { season_id: 35191, title: '续 刀剑乱舞-花丸-' },
        { season_id: 35257, title: 'Infini-T Force' },
        { season_id: 35259, title: 'JOJO的奇妙冒险 星尘远征军' },
        { season_id: 35260, title: 'JOJO的奇妙冒险 星尘远征军 埃及篇' },
        { season_id: 35274, title: 'UQ HOLDER！悠久持有者！' },
        { season_id: 35276, title: '文豪野犬 第三季' },
        { season_id: 35290, title: '我为歌狂之旋律重启' },
        { season_id: 35296, title: '弹丸论破3 -绝望篇-' },
        { season_id: 35297, title: '宿身小人' },
        { season_id: 35298, title: '秦侠' },
        { season_id: 35324, title: '七大罪 圣战的预兆' },
        { season_id: 35333, title: '强袭魔女 501 部队出动！' },
        { season_id: 35336, title: '天官赐福' },
        { season_id: 35342, title: 'Re：从零开始的异世界生活 第二季 Part1' },
        { season_id: 35368, title: '果然我的青春恋爱喜剧搞错了。完' },
        {
          season_id: 35409,
          title: 'Fate/stay night [Unlimited Blade Works] 第一季',
        },
        {
          season_id: 35410,
          title: 'Fate/stay night [Unlimited Blade Works] 第二季',
        },
        {
          season_id: 35412,
          title: "Fate/stay night [Heaven's Feel]Ⅰ.预示之花",
        },
        {
          season_id: 35413,
          title: "Fate/stay night [Heaven's Feel]Ⅱ.迷途之蝶",
        },
        { season_id: 35414, title: 'Fate/Zero 第一季' },
        { season_id: 35415, title: 'Fate/Zero 第二季' },
        { season_id: 35416, title: '樱花任务' },
        {
          season_id: 35420,
          title: '转生成女性向游戏只有毁灭 END 的坏人大小姐 ',
        },
        { season_id: 35421, title: '我不是说了能力要平均值吗？' },
        { season_id: 35424, title: '七大罪 戒律的复活' },
        { season_id: 35431, title: '独占我的英雄' },
        { season_id: 35452, title: '我家大师兄是个反派' },
        { season_id: 35453, title: '恋爱中的小行星' },
        { season_id: 35467, title: '剧场版总集篇 OVERLORD 不死者之王' },
        { season_id: 35468, title: '劇場版總集篇 OVERLORD 漆黑的英雄' },
        { season_id: 35472, title: '魔法律事务所 第二季' },
        { season_id: 35473, title: '宇崎学妹想要玩！' },
        { season_id: 35487, title: '白猫Project ZERO CHRONICLE 零之纪元' },
        {
          season_id: 35496,
          title: '异世界居酒屋～古都阿伊特力亚的居酒屋阿信～',
        },
        { season_id: 35498, title: '出租女友' },
        { season_id: 35504, title: '我的英雄学院 第二季' },
        { season_id: 35505, title: '我的英雄学院 第三季' },
        { season_id: 35515, title: '我的英雄学院 第四季' },
        { season_id: 35517, title: '我的英雄学院' },
        { season_id: 35519, title: '弹丸论破3 -未来篇-' },
        { season_id: 35522, title: '弹丸论破' },
        { season_id: 35526, title: '富豪刑警Balance:UNLIMITED' },
        { season_id: 35541, title: '影鳄 - KAGEWANI- 第二季' },
        { season_id: 35552, title: '高校星歌剧' },
        { season_id: 35553, title: '高校星歌剧 第二季' },
        { season_id: 35559, title: '梦王国与沉睡中的100位王子殿下' },
        { season_id: 35591, title: '暮蝉鸣泣时' },
        { season_id: 35608, title: '如果有妹妹就好了。' },
        { season_id: 35610, title: '放学后堤防日志' },
        { season_id: 35615, title: '关于我女友是个一本正经的碧池这件事' },
        { season_id: 35624, title: '失忆煽动WIXOSS' },
        { season_id: 35664, title: '新樱花大战' },
        { season_id: 35667, title: '十二大战' },
        { season_id: 35683, title: '天真与闪电' },
        { season_id: 35691, title: '啄木鸟侦探社' },
        { season_id: 35692, title: '家庭教师HITMAN REBORN!' },
        { season_id: 35753, title: 'Re：从零开始的异世界生活 新编集版' },
        { season_id: 35757, title: '某科学的超电磁炮T' },
        { season_id: 35794, title: '怪物猎人物语 RIDE ON 第二季' },
        { season_id: 35795, title: '有顶天家族' },
        { season_id: 35833, title: '食戟之灵 豪之皿' },
        { season_id: 35912, title: '无限系统树' },
        { season_id: 35913, title: '食戟之灵 餐之皿' },
        { season_id: 35932, title: '刀剑神域' },
        { season_id: 35933, title: '刀剑神域 第二季' },
        { season_id: 35936, title: '我们无法一起学习！' },
        { season_id: 35986, title: '超级恋人' },
        { season_id: 36031, title: '超级恋人 第二季' },
        { season_id: 36154, title: '伊藤润二惊选集' },
        { season_id: 36155, title: '游戏3人娘' },
        { season_id: 36199, title: '约会大作战 万由里裁决' },
        { season_id: 36256, title: '赛马娘 Pretty Derby' },
        { season_id: 36279, title: '一拳超人' },
        { season_id: 36297, title: '进击的巨人 The Final Season' },
        { season_id: 36298, title: '彼得·格里尔的贤者时间' },
        { season_id: 36300, title: '头文字D Legend1 -觉醒-' },
        { season_id: 36301, title: '头文字D Legend2 -斗走-' },
        { season_id: 36302, title: '辉夜姬想让我告白～天才们的恋爱头脑战～' },
        { season_id: 36307, title: '政宗君的复仇' },
        { season_id: 36309, title: '幸腹涂鸦' },
        { season_id: 36311, title: '头文字D Legend3 -梦现-' },
        {
          season_id: 36312,
          title: '家庭教师HITMAN REBORN！彭格列式修学旅行、来了！',
        },
        { season_id: 36337, title: '最弱无败神装机龙' },
        { season_id: 36338, title: '声之形' },
        { season_id: 36339, title: '火影忍者疾风传 剧场版 血狱' },
        { season_id: 36340, title: '火影忍者疾风传 剧场版 失落之塔' },
        { season_id: 36341, title: '火影忍者 剧场版 终章' },
        { season_id: 36381, title: '一拳超人 第二季' },
        { season_id: 36382, title: '关于我转生成为史莱姆这档事 OVA' },
        { season_id: 36386, title: '末日时在做什么？有没有空？可以来拯救吗？' },
        { season_id: 36439, title: '出租魔法使' },
        { season_id: 36441, title: '地球队长' },
        { season_id: 36446, title: '高校之神' },
        { season_id: 36448, title: '歌之☆王子殿下 真爱1000%' },
        { season_id: 36458, title: '灰与幻想的格林姆迦尔' },
        { season_id: 36493, title: '全金属狂潮 Invisible Victory' },
        { season_id: 36494, title: '全金属狂潮 One Night Stand' },
        { season_id: 36495, title: '全金属狂潮 Into the Blue' },
        { season_id: 36496, title: '全金属狂潮 Boy Meets Girl' },
        { season_id: 36522, title: '工作细胞 BLACK' },
        { season_id: 36523, title: '工作细胞  第二季' },
        { season_id: 36534, title: '弱势角色友崎君' },
        { season_id: 36538, title: '五等分的新娘∬' },
        { season_id: 36568, title: '剧偶像' },
        { season_id: 36569, title: '装甲娘战机' },
        { season_id: 36570, title: '天地创造设计部' },
        { season_id: 36571, title: '凡人修仙传之凡人风起天南' },
        { season_id: 36572, title: '汉化日记 第二季' },
        { season_id: 36574, title: '请吃红小豆吧！' },
        { season_id: 36578, title: '请吃红小豆吧！外传 莫相忘' },
        { season_id: 36598, title: '约定的梦幻岛' },
        { season_id: 36600, title: 'DARLING in the FRANXX' },
        { season_id: 36603, title: '游戏王：次元的黑暗面' },
        { season_id: 36606, title: '文豪野犬 DEAD APPLE' },
        { season_id: 36607, title: '佐贺偶像是传奇' },
        { season_id: 36609, title: '伪恋' },
        { season_id: 36610, title: '伪恋：' },
        { season_id: 36611, title: '俺物语!!' },
        { season_id: 36612, title: '情色漫画老师' },
        { season_id: 36613, title: '隐瞒之事' },
        { season_id: 36622, title: '犬夜叉 天下霸道之剑' },
        { season_id: 36623, title: '犬夜叉 穿越时空的思念' },
        {
          season_id: 36624,
          title:
            '魔王学院的不适任者～史上最强的魔王始祖，转生就读子孙们的学校～',
        },
        { season_id: 36627, title: '刀剑乱舞-花丸-' },
        { season_id: 36634, title: '魔弹之王与战姫' },
        { season_id: 36652, title: '彼方的阿斯特拉' },
        { season_id: 36687, title: '小林家的龙女仆' },
        { season_id: 36689, title: '关于我转生变成史莱姆这档事 第二季' },
        { season_id: 36690, title: '无职转生～到了异世界就拿出真本事～' },
        {
          season_id: 36691,
          title: '好比是最终迷宫前的少年到新手村生活一般的故事',
        },
        { season_id: 36692, title: '约定的梦幻岛 第二季' },
        { season_id: 36705, title: '苍之骑士团' },
        { season_id: 36709, title: '无限滑板 SK∞' },
        { season_id: 36710, title: '转生成蜘蛛又怎样！' },
        { season_id: 36711, title: '怪病医拉姆尼' },
        { season_id: 36716, title: '文豪野犬 汪！' },
        { season_id: 36717, title: 'Re：从零开始的异世界生活 第二季 Part2' },
        { season_id: 36718, title: '大人的防具店' },
        { season_id: 36747, title: '五星物语 剧场版' },
        { season_id: 36749, title: '弦音 -风舞高中弓道部-' },
        { season_id: 36832, title: '玛娜利亚魔法学院' },
        { season_id: 36847, title: '织田肉桂信长' },
        { season_id: 36934, title: '只有我能进入的隐藏地下城' },
        { season_id: 36935, title: '回复术士的重来人生' },
        { season_id: 36936, title: '世界魔女出发！' },
        { season_id: 36937, title: '重创的伤口' },
        { season_id: 36938, title: '悠哉日常大王 Nonstop' },
        { season_id: 36940, title: '里世界郊游' },
        { season_id: 37179, title: '来自深渊' },
        { season_id: 37286, title: '卡姆伊之剑' },
        { season_id: 37287, title: '冷然之天秤' },
        { season_id: 37288, title: '迷宫物语' },
        { season_id: 37489, title: '摇曳露营△ 第二季' },
        { season_id: 37490, title: '堀与宫村' },
        { season_id: 37493, title: '怪物事变' },
        { season_id: 37494, title: '魔术士奥芬的无赖之旅 第二季' },
        { season_id: 37495, title: '摇滚少女!! STARS!!' },
        { season_id: 37497, title: '花样滑冰Stars' },
        { season_id: 37499, title: '2.43 清阴高校男子排球部' },
        { season_id: 37500, title: '记录的地平线 圆桌崩坏' },
        { season_id: 37503, title: 'BACK ARROW' },
        { season_id: 37504, title: '大人的防具店 第二季' },
        { season_id: 37505, title: '暗芝居 第八季' },
        { season_id: 37549, title: '2020最美的夜 bilibili晚会' },
        { season_id: 37565, title: 'WAVE!!~来冲浪吧!!~' },
        { season_id: 37614, title: '暗芝居 第六季' },
        { season_id: 37615, title: '暗芝居 第七季' },
        { season_id: 37619, title: '进击的巨人 编年史' },
        { season_id: 37624, title: '赛马娘 Pretty Derby 第二季' },
        { season_id: 37629, title: '暗芝居' },
        { season_id: 37630, title: '暗芝居 第二季' },
        { season_id: 37631, title: '暗芝居 第三季' },
        { season_id: 37632, title: '暗芝居 第四季' },
        { season_id: 37643, title: '达尔文游戏' },
        { season_id: 37653, title: '天宝伏妖录' },
        { season_id: 37654, title: '学园奶爸' },
        { season_id: 37662, title: '奇蛋物语' },
        { season_id: 37739, title: '解药' },
        { season_id: 37749, title: '满脑都是○○的我没办法谈恋爱 ' },
        { season_id: 37950, title: '元龙' },
        { season_id: 37951, title: '芯觉' },
        { season_id: 38095, title: '舞伎家的料理人' },
        { season_id: 1000547, title: '教教我吧 北斋！' },
        { season_id: 1000865, title: '当我刮掉胡子时，会发生什么事' },
        { season_id: 1000946, title: '纯白之音' },
        {
          season_id: 1001070,
          title: '如果究极进化的完全沉浸RPG比现实更垃圾的话',
        },
        { season_id: 1001189, title: '这如果叫作爱情 感觉会很恶心' },
        {
          season_id: 1001243,
          title: '打了300年的史莱姆，不知不觉就练到了满级',
        },
        { season_id: 1001338, title: 'SSSS.DYNAZENON' },
        { season_id: 1001400, title: '东京卍复仇者' },
        { season_id: 1001534, title: '美少年侦探团' },
        { season_id: 1001642, title: '龙先生，想要买个家' },
        { season_id: 1001754, title: '再见了，我的克拉默' },
        { season_id: 1001902, title: '煋红' },
        { season_id: 1002010, title: '大运动会 ReSTART！' },
        { season_id: 1002154, title: '蔚蓝反射 澪' },
        { season_id: 1002225, title: '致不灭的你' },
        {
          season_id: 1002302,
          title: '关于我转生变成史莱姆这档事 转生史莱姆日记',
        },
        { season_id: 1002403, title: '青梅竹马绝对不会输的恋爱喜剧' },
        { season_id: 1002520, title: '战斗员派遣中！' },
        { season_id: 1002626, title: '佐贺偶像是传奇 卷土重来' },
        { season_id: 1002703, title: '圣女魔力无所不能' },
        { season_id: 1002837, title: '如果烧陶的话也做个马克杯吧' },
        { season_id: 1002926, title: '我的英雄学院 第五季' },
        { season_id: 1003031, title: '86 -不存在的战区-' },
        { season_id: 1003171, title: '入间同学入魔了 第二季' },
        { season_id: 1003282, title: '黑塔利亚 World★Stars' },
        { season_id: 1003350, title: '装甲重拳 第二季' },
        { season_id: 1003433, title: '美丽新世界 The Animation' },
        { season_id: 1003535, title: 'Fairy兰丸～让我来帮助你的心～' },
        { season_id: 1003644, title: '七骑士 英雄的继承者' },
        { season_id: 1003789, title: '扰乱 THE PRINCESS OF SNOW AND BLOOD' },
        { season_id: 1003860, title: '影宅' },
        {
          season_id: 1003989,
          title: "Fate/stay night [Heaven's Feel]Ⅲ.春樱之歌",
        },
        { season_id: 1004113, title: '烧陶的放学后' },
        { season_id: 1004201, title: '进击的巨人（泰配版）' },
        { season_id: 1004344, title: '进击的巨人 第二季（泰配版）' },
        { season_id: 1004516, title: '被神捡到的男人' },
        { season_id: 1004601, title: '进击！巨人中学校' },
        { season_id: 1004816, title: '魔法科高校的劣等生 来访者篇' },
        { season_id: 1005144, title: '火影忍者' },
        { season_id: 1005195, title: '火影忍者疾风传' },
        { season_id: 1005426, title: '博人传之火影忍者次世代' },
        { season_id: 1005556, title: '天宝伏妖录 第二季' },
        { season_id: 1005700, title: '两不疑' },
        { season_id: 1005762, title: '进击的巨人 第三季（泰配版）' },
        { season_id: 1005888, title: '灵笼' },
        {
          season_id: 1006086,
          title: 'Fate/Grand Order 神圣圆桌领域卡美洛 前篇 Wandering; Agateram',
        },
        { season_id: 1006275, title: '时光代理人' },
        { season_id: 1006354, title: ' 喂，看见耳朵啦' },
        { season_id: 1006414, title: '喂，看见耳朵啦 第二季' },
        { season_id: 1006548, title: '迷你龙小剧场' },
      ],
    }
  },
})
</script>
