// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Anigamers", testAnigamers)
	t.Run("Bilibilis", testBilibilis)
	t.Run("BilibiliSeas", testBilibiliSeas)
	t.Run("Histories", testHistories)
}

func TestDelete(t *testing.T) {
	t.Run("Anigamers", testAnigamersDelete)
	t.Run("Bilibilis", testBilibilisDelete)
	t.Run("BilibiliSeas", testBilibiliSeasDelete)
	t.Run("Histories", testHistoriesDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Anigamers", testAnigamersQueryDeleteAll)
	t.Run("Bilibilis", testBilibilisQueryDeleteAll)
	t.Run("BilibiliSeas", testBilibiliSeasQueryDeleteAll)
	t.Run("Histories", testHistoriesQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Anigamers", testAnigamersSliceDeleteAll)
	t.Run("Bilibilis", testBilibilisSliceDeleteAll)
	t.Run("BilibiliSeas", testBilibiliSeasSliceDeleteAll)
	t.Run("Histories", testHistoriesSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Anigamers", testAnigamersExists)
	t.Run("Bilibilis", testBilibilisExists)
	t.Run("BilibiliSeas", testBilibiliSeasExists)
	t.Run("Histories", testHistoriesExists)
}

func TestFind(t *testing.T) {
	t.Run("Anigamers", testAnigamersFind)
	t.Run("Bilibilis", testBilibilisFind)
	t.Run("BilibiliSeas", testBilibiliSeasFind)
	t.Run("Histories", testHistoriesFind)
}

func TestBind(t *testing.T) {
	t.Run("Anigamers", testAnigamersBind)
	t.Run("Bilibilis", testBilibilisBind)
	t.Run("BilibiliSeas", testBilibiliSeasBind)
	t.Run("Histories", testHistoriesBind)
}

func TestOne(t *testing.T) {
	t.Run("Anigamers", testAnigamersOne)
	t.Run("Bilibilis", testBilibilisOne)
	t.Run("BilibiliSeas", testBilibiliSeasOne)
	t.Run("Histories", testHistoriesOne)
}

func TestAll(t *testing.T) {
	t.Run("Anigamers", testAnigamersAll)
	t.Run("Bilibilis", testBilibilisAll)
	t.Run("BilibiliSeas", testBilibiliSeasAll)
	t.Run("Histories", testHistoriesAll)
}

func TestCount(t *testing.T) {
	t.Run("Anigamers", testAnigamersCount)
	t.Run("Bilibilis", testBilibilisCount)
	t.Run("BilibiliSeas", testBilibiliSeasCount)
	t.Run("Histories", testHistoriesCount)
}

func TestHooks(t *testing.T) {
	t.Run("Anigamers", testAnigamersHooks)
	t.Run("Bilibilis", testBilibilisHooks)
	t.Run("BilibiliSeas", testBilibiliSeasHooks)
	t.Run("Histories", testHistoriesHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Anigamers", testAnigamersInsert)
	t.Run("Anigamers", testAnigamersInsertWhitelist)
	t.Run("Bilibilis", testBilibilisInsert)
	t.Run("Bilibilis", testBilibilisInsertWhitelist)
	t.Run("BilibiliSeas", testBilibiliSeasInsert)
	t.Run("BilibiliSeas", testBilibiliSeasInsertWhitelist)
	t.Run("Histories", testHistoriesInsert)
	t.Run("Histories", testHistoriesInsertWhitelist)
}

func TestReload(t *testing.T) {
	t.Run("Anigamers", testAnigamersReload)
	t.Run("Bilibilis", testBilibilisReload)
	t.Run("BilibiliSeas", testBilibiliSeasReload)
	t.Run("Histories", testHistoriesReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Anigamers", testAnigamersReloadAll)
	t.Run("Bilibilis", testBilibilisReloadAll)
	t.Run("BilibiliSeas", testBilibiliSeasReloadAll)
	t.Run("Histories", testHistoriesReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Anigamers", testAnigamersSelect)
	t.Run("Bilibilis", testBilibilisSelect)
	t.Run("BilibiliSeas", testBilibiliSeasSelect)
	t.Run("Histories", testHistoriesSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Anigamers", testAnigamersUpdate)
	t.Run("Bilibilis", testBilibilisUpdate)
	t.Run("BilibiliSeas", testBilibiliSeasUpdate)
	t.Run("Histories", testHistoriesUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Anigamers", testAnigamersSliceUpdateAll)
	t.Run("Bilibilis", testBilibilisSliceUpdateAll)
	t.Run("BilibiliSeas", testBilibiliSeasSliceUpdateAll)
	t.Run("Histories", testHistoriesSliceUpdateAll)
}
